// File: src/data/indianStatesDistricts.ts
// Comprehensive data for Indian States and their Districts

export interface District {
  name: string;
  code?: string;
}

export interface State {
  name: string;
  code: string;
  districts: District[];
}

export const INDIAN_STATES_WITH_DISTRICTS: State[] = [
  {
    name: "Andhra Pradesh",
    code: "AP",
    districts: [
      { name: "Anantapur" },
      { name: "Chittoor" },
      { name: "East Godavari" },
      { name: "Guntur" },
      { name: "Kadapa" },
      { name: "Krishna" },
      { name: "Kurnool" },
      { name: "Nellore" },
      { name: "Prakasam" },
      { name: "Srikakulam" },
      { name: "Visakhapatnam" },
      { name: "Vizianagaram" },
      { name: "West Godavari" },
    ],
  },
  {
    name: "Arunachal Pradesh",
    code: "AR",
    districts: [
      { name: "Anjaw" },
      { name: "Changlang" },
      { name: "Dibang Valley" },
      { name: "East Kameng" },
      { name: "East Siang" },
      { name: "Kamle" },
      { name: "Kra Daadi" },
      { name: "Kurung Kumey" },
      { name: "Lepa Rada" },
      { name: "Lohit" },
      { name: "Longding" },
      { name: "Lower Dibang Valley" },
      { name: "Lower Siang" },
      { name: "Lower Subansiri" },
      { name: "Namsai" },
      { name: "Pakke Kessang" },
      { name: "Papum Pare" },
      { name: "Shi Yomi" },
      { name: "Siang" },
      { name: "Tawang" },
      { name: "Tirap" },
      { name: "Upper Siang" },
      { name: "Upper Subansiri" },
      { name: "West Kameng" },
      { name: "West Siang" },
    ],
  },
  {
    name: "Assam",
    code: "AS",
    districts: [
      { name: "Baksa" },
      { name: "Barpeta" },
      { name: "Biswanath" },
      { name: "Bongaigaon" },
      { name: "Cachar" },
      { name: "Charaideo" },
      { name: "Chirang" },
      { name: "Darrang" },
      { name: "Dhemaji" },
      { name: "Dhubri" },
      { name: "Dibrugarh" },
      { name: "Goalpara" },
      { name: "Golaghat" },
      { name: "Hailakandi" },
      { name: "Hojai" },
      { name: "Jorhat" },
      { name: "Kamrup" },
      { name: "Kamrup Metropolitan" },
      { name: "Karbi Anglong" },
      { name: "Karimganj" },
      { name: "Kokrajhar" },
      { name: "Lakhimpur" },
      { name: "Majuli" },
      { name: "Morigaon" },
      { name: "Nagaon" },
      { name: "Nalbari" },
      { name: "Dima Hasao" },
      { name: "Sivasagar" },
      { name: "Sonitpur" },
      { name: "South Salmara-Mankachar" },
      { name: "Tinsukia" },
      { name: "Udalguri" },
      { name: "West Karbi Anglong" },
    ],
  },
  {
    name: "Bihar",
    code: "BR",
    districts: [
      { name: "Araria" },
      { name: "Arwal" },
      { name: "Aurangabad" },
      { name: "Banka" },
      { name: "Begusarai" },
      { name: "Bhagalpur" },
      { name: "Bhojpur" },
      { name: "Buxar" },
      { name: "Darbhanga" },
      { name: "East Champaran" },
      { name: "Gaya" },
      { name: "Gopalganj" },
      { name: "Jamui" },
      { name: "Jehanabad" },
      { name: "Kaimur" },
      { name: "Katihar" },
      { name: "Khagaria" },
      { name: "Kishanganj" },
      { name: "Lakhisarai" },
      { name: "Madhepura" },
      { name: "Madhubani" },
      { name: "Munger" },
      { name: "Muzaffarpur" },
      { name: "Nalanda" },
      { name: "Nawada" },
      { name: "Patna" },
      { name: "Purnia" },
      { name: "Rohtas" },
      { name: "Saharsa" },
      { name: "Samastipur" },
      { name: "Saran" },
      { name: "Sheikhpura" },
      { name: "Sheohar" },
      { name: "Sitamarhi" },
      { name: "Siwan" },
      { name: "Supaul" },
      { name: "Vaishali" },
      { name: "West Champaran" },
    ],
  },
  {
    name: "Chhattisgarh",
    code: "CG",
    districts: [
      { name: "Balod" },
      { name: "Baloda Bazar" },
      { name: "Balrampur" },
      { name: "Bastar" },
      { name: "Bemetara" },
      { name: "Bijapur" },
      { name: "Bilaspur" },
      { name: "Dantewada" },
      { name: "Dhamtari" },
      { name: "Durg" },
      { name: "Gariaband" },
      { name: "Gaurela Pendra Marwahi" },
      { name: "Janjgir Champa" },
      { name: "Jashpur" },
      { name: "Kabirdham" },
      { name: "Kanker" },
      { name: "Kondagaon" },
      { name: "Korba" },
      { name: "Koriya" },
      { name: "Mahasamund" },
      { name: "Mungeli" },
      { name: "Narayanpur" },
      { name: "Raigarh" },
      { name: "Raipur" },
      { name: "Rajnandgaon" },
      { name: "Sukma" },
      { name: "Surajpur" },
      { name: "Surguja" },
    ],
  },
  {
    name: "Goa",
    code: "GA",
    districts: [{ name: "North Goa" }, { name: "South Goa" }],
  },
  {
    name: "Gujarat",
    code: "GJ",
    districts: [
      { name: "Ahmedabad" },
      { name: "Amreli" },
      { name: "Anand" },
      { name: "Aravalli" },
      { name: "Banaskantha" },
      { name: "Bharuch" },
      { name: "Bhavnagar" },
      { name: "Botad" },
      { name: "Chhota Udaipur" },
      { name: "Dahod" },
      { name: "Dang" },
      { name: "Devbhoomi Dwarka" },
      { name: "Gandhinagar" },
      { name: "Gir Somnath" },
      { name: "Jamnagar" },
      { name: "Junagadh" },
      { name: "Kheda" },
      { name: "Kutch" },
      { name: "Mahisagar" },
      { name: "Mehsana" },
      { name: "Morbi" },
      { name: "Narmada" },
      { name: "Navsari" },
      { name: "Panchmahal" },
      { name: "Patan" },
      { name: "Porbandar" },
      { name: "Rajkot" },
      { name: "Sabarkantha" },
      { name: "Surat" },
      { name: "Surendranagar" },
      { name: "Tapi" },
      { name: "Vadodara" },
      { name: "Valsad" },
    ],
  },
  {
    name: "Haryana",
    code: "HR",
    districts: [
      { name: "Ambala" },
      { name: "Bhiwani" },
      { name: "Charkhi Dadri" },
      { name: "Faridabad" },
      { name: "Fatehabad" },
      { name: "Gurugram" },
      { name: "Hisar" },
      { name: "Jhajjar" },
      { name: "Jind" },
      { name: "Kaithal" },
      { name: "Karnal" },
      { name: "Kurukshetra" },
      { name: "Mahendragarh" },
      { name: "Nuh" },
      { name: "Palwal" },
      { name: "Panchkula" },
      { name: "Panipat" },
      { name: "Rewari" },
      { name: "Rohtak" },
      { name: "Sirsa" },
      { name: "Sonipat" },
      { name: "Yamunanagar" },
    ],
  },
  {
    name: "Himachal Pradesh",
    code: "HP",
    districts: [
      { name: "Bilaspur" },
      { name: "Chamba" },
      { name: "Hamirpur" },
      { name: "Kangra" },
      { name: "Kinnaur" },
      { name: "Kullu" },
      { name: "Lahaul Spiti" },
      { name: "Mandi" },
      { name: "Shimla" },
      { name: "Sirmaur" },
      { name: "Solan" },
      { name: "Una" },
    ],
  },
  {
    name: "Jharkhand",
    code: "JH",
    districts: [
      { name: "Bokaro" },
      { name: "Chatra" },
      { name: "Deoghar" },
      { name: "Dhanbad" },
      { name: "Dumka" },
      { name: "East Singhbhum" },
      { name: "Garhwa" },
      { name: "Giridih" },
      { name: "Godda" },
      { name: "Gumla" },
      { name: "Hazaribagh" },
      { name: "Jamtara" },
      { name: "Khunti" },
      { name: "Koderma" },
      { name: "Latehar" },
      { name: "Lohardaga" },
      { name: "Pakur" },
      { name: "Palamu" },
      { name: "Ramgarh" },
      { name: "Ranchi" },
      { name: "Sahebganj" },
      { name: "Seraikela Kharsawan" },
      { name: "Simdega" },
      { name: "West Singhbhum" },
    ],
  },
  {
    name: "Karnataka",
    code: "KA",
    districts: [
      { name: "Bagalkot" },
      { name: "Bangalore Rural" },
      { name: "Bangalore Urban" },
      { name: "Belgaum" },
      { name: "Bellary" },
      { name: "Bidar" },
      { name: "Chamarajanagar" },
      { name: "Chikkaballapur" },
      { name: "Chikkamagaluru" },
      { name: "Chitradurga" },
      { name: "Dakshina Kannada" },
      { name: "Davanagere" },
      { name: "Dharwad" },
      { name: "Gadag" },
      { name: "Gulbarga" },
      { name: "Hassan" },
      { name: "Haveri" },
      { name: "Kodagu" },
      { name: "Kolar" },
      { name: "Koppal" },
      { name: "Mandya" },
      { name: "Mysore" },
      { name: "Raichur" },
      { name: "Ramanagara" },
      { name: "Shimoga" },
      { name: "Tumkur" },
      { name: "Udupi" },
      { name: "Uttara Kannada" },
      { name: "Vijayapura" },
      { name: "Yadgir" },
    ],
  },
  {
    name: "Kerala",
    code: "KL",
    districts: [
      { name: "Alappuzha" },
      { name: "Ernakulam" },
      { name: "Idukki" },
      { name: "Kannur" },
      { name: "Kasaragod" },
      { name: "Kollam" },
      { name: "Kottayam" },
      { name: "Kozhikode" },
      { name: "Malappuram" },
      { name: "Palakkad" },
      { name: "Pathanamthitta" },
      { name: "Thiruvananthapuram" },
      { name: "Thrissur" },
      { name: "Wayanad" },
    ],
  },
  {
    name: "Madhya Pradesh",
    code: "MP",
    districts: [
      { name: "Agar Malwa" },
      { name: "Alirajpur" },
      { name: "Anuppur" },
      { name: "Ashoknagar" },
      { name: "Balaghat" },
      { name: "Barwani" },
      { name: "Betul" },
      { name: "Bhind" },
      { name: "Bhopal" },
      { name: "Burhanpur" },
      { name: "Chhatarpur" },
      { name: "Chhindwara" },
      { name: "Damoh" },
      { name: "Datia" },
      { name: "Dewas" },
      { name: "Dhar" },
      { name: "Dindori" },
      { name: "Guna" },
      { name: "Gwalior" },
      { name: "Harda" },
      { name: "Hoshangabad" },
      { name: "Indore" },
      { name: "Jabalpur" },
      { name: "Jhabua" },
      { name: "Katni" },
      { name: "Khandwa" },
      { name: "Khargone" },
      { name: "Mandla" },
      { name: "Mandsaur" },
      { name: "Morena" },
      { name: "Narsinghpur" },
      { name: "Neemuch" },
      { name: "Panna" },
      { name: "Raisen" },
      { name: "Rajgarh" },
      { name: "Ratlam" },
      { name: "Rewa" },
      { name: "Sagar" },
      { name: "Satna" },
      { name: "Sehore" },
      { name: "Seoni" },
      { name: "Shahdol" },
      { name: "Shajapur" },
      { name: "Sheopur" },
      { name: "Shivpuri" },
      { name: "Sidhi" },
      { name: "Singrauli" },
      { name: "Tikamgarh" },
      { name: "Ujjain" },
      { name: "Umaria" },
      { name: "Vidisha" },
    ],
  },
  {
    name: "Maharashtra",
    code: "MH",
    districts: [
      { name: "Ahmednagar" },
      { name: "Akola" },
      { name: "Amravati" },
      { name: "Aurangabad" },
      { name: "Beed" },
      { name: "Bhandara" },
      { name: "Buldhana" },
      { name: "Chandrapur" },
      { name: "Dhule" },
      { name: "Gadchiroli" },
      { name: "Gondia" },
      { name: "Hingoli" },
      { name: "Jalgaon" },
      { name: "Jalna" },
      { name: "Kolhapur" },
      { name: "Latur" },
      { name: "Mumbai City" },
      { name: "Mumbai Suburban" },
      { name: "Nagpur" },
      { name: "Nanded" },
      { name: "Nandurbar" },
      { name: "Nashik" },
      { name: "Osmanabad" },
      { name: "Palghar" },
      { name: "Parbhani" },
      { name: "Pune" },
      { name: "Raigad" },
      { name: "Ratnagiri" },
      { name: "Sangli" },
      { name: "Satara" },
      { name: "Sindhudurg" },
      { name: "Solapur" },
      { name: "Thane" },
      { name: "Wardha" },
      { name: "Washim" },
      { name: "Yavatmal" },
    ],
  },
  {
    name: "Manipur",
    code: "MN",
    districts: [
      { name: "Bishnupur" },
      { name: "Chandel" },
      { name: "Churachandpur" },
      { name: "Imphal East" },
      { name: "Imphal West" },
      { name: "Jiribam" },
      { name: "Kakching" },
      { name: "Kamjong" },
      { name: "Kangpokpi" },
      { name: "Noney" },
      { name: "Pherzawl" },
      { name: "Senapati" },
      { name: "Tamenglong" },
      { name: "Tengnoupal" },
      { name: "Thoubal" },
      { name: "Ukhrul" },
    ],
  },
  {
    name: "Meghalaya",
    code: "ML",
    districts: [
      { name: "East Garo Hills" },
      { name: "East Jaintia Hills" },
      { name: "East Khasi Hills" },
      { name: "North Garo Hills" },
      { name: "Ri Bhoi" },
      { name: "South Garo Hills" },
      { name: "South West Garo Hills" },
      { name: "South West Khasi Hills" },
      { name: "West Garo Hills" },
      { name: "West Jaintia Hills" },
      { name: "West Khasi Hills" },
    ],
  },
  {
    name: "Mizoram",
    code: "MZ",
    districts: [
      { name: "Aizawl" },
      { name: "Champhai" },
      { name: "Hnahthial" },
      { name: "Kolasib" },
      { name: "Khawzawl" },
      { name: "Lawngtlai" },
      { name: "Lunglei" },
      { name: "Mamit" },
      { name: "Saiha" },
      { name: "Saitual" },
      { name: "Serchhip" },
    ],
  },
  {
    name: "Nagaland",
    code: "NL",
    districts: [
      { name: "Chumukedima" },
      { name: "Dimapur" },
      { name: "Kiphire" },
      { name: "Kohima" },
      { name: "Longleng" },
      { name: "Mokokchung" },
      { name: "Mon" },
      { name: "Niuland" },
      { name: "Noklak" },
      { name: "Peren" },
      { name: "Phek" },
      { name: "Shamator" },
      { name: "Tseminyu" },
      { name: "Tuensang" },
      { name: "Wokha" },
      { name: "Zunheboto" },
    ],
  },
  {
    name: "Odisha",
    code: "OR",
    districts: [
      { name: "Angul" },
      { name: "Balangir" },
      { name: "Balasore" },
      { name: "Bargarh" },
      { name: "Bhadrak" },
      { name: "Boudh" },
      { name: "Cuttack" },
      { name: "Deogarh" },
      { name: "Dhenkanal" },
      { name: "Gajapati" },
      { name: "Ganjam" },
      { name: "Jagatsinghpur" },
      { name: "Jajpur" },
      { name: "Jharsuguda" },
      { name: "Kalahandi" },
      { name: "Kandhamal" },
      { name: "Kendrapara" },
      { name: "Kendujhar" },
      { name: "Khordha" },
      { name: "Koraput" },
      { name: "Malkangiri" },
      { name: "Mayurbhanj" },
      { name: "Nabarangpur" },
      { name: "Nayagarh" },
      { name: "Nuapada" },
      { name: "Puri" },
      { name: "Rayagada" },
      { name: "Sambalpur" },
      { name: "Subarnapur" },
      { name: "Sundargarh" },
    ],
  },
  {
    name: "Punjab",
    code: "PB",
    districts: [
      { name: "Amritsar" },
      { name: "Barnala" },
      { name: "Bathinda" },
      { name: "Faridkot" },
      { name: "Fatehgarh Sahib" },
      { name: "Fazilka" },
      { name: "Ferozepur" },
      { name: "Gurdaspur" },
      { name: "Hoshiarpur" },
      { name: "Jalandhar" },
      { name: "Kapurthala" },
      { name: "Ludhiana" },
      { name: "Malerkotla" },
      { name: "Mansa" },
      { name: "Moga" },
      { name: "Mohali" },
      { name: "Muktsar" },
      { name: "Pathankot" },
      { name: "Patiala" },
      { name: "Rupnagar" },
      { name: "Sangrur" },
      { name: "Shaheed Bhagat Singh Nagar" },
      { name: "Tarn Taran" },
    ],
  },
  {
    name: "Rajasthan",
    code: "RJ",
    districts: [
      { name: "Ajmer" },
      { name: "Alwar" },
      { name: "Banswara" },
      { name: "Baran" },
      { name: "Barmer" },
      { name: "Bharatpur" },
      { name: "Bhilwara" },
      { name: "Bikaner" },
      { name: "Bundi" },
      { name: "Chittorgarh" },
      { name: "Churu" },
      { name: "Dausa" },
      { name: "Dholpur" },
      { name: "Dungarpur" },
      { name: "Ganganagar" },
      { name: "Hanumangarh" },
      { name: "Jaipur" },
      { name: "Jaisalmer" },
      { name: "Jalore" },
      { name: "Jhalawar" },
      { name: "Jhunjhunu" },
      { name: "Jodhpur" },
      { name: "Karauli" },
      { name: "Kota" },
      { name: "Nagaur" },
      { name: "Pali" },
      { name: "Pratapgarh" },
      { name: "Rajsamand" },
      { name: "Sawai Madhopur" },
      { name: "Sikar" },
      { name: "Sirohi" },
      { name: "Tonk" },
      { name: "Udaipur" },
    ],
  },
  {
    name: "Sikkim",
    code: "SK",
    districts: [{ name: "East Sikkim" }, { name: "North Sikkim" }, { name: "South Sikkim" }, { name: "West Sikkim" }],
  },
  {
    name: "Tamil Nadu",
    code: "TN",
    districts: [
      { name: "Ariyalur" },
      { name: "Chengalpattu" },
      { name: "Chennai" },
      { name: "Coimbatore" },
      { name: "Cuddalore" },
      { name: "Dharmapuri" },
      { name: "Dindigul" },
      { name: "Erode" },
      { name: "Kallakurichi" },
      { name: "Kancheepuram" },
      { name: "Karur" },
      { name: "Krishnagiri" },
      { name: "Madurai" },
      { name: "Mayiladuthurai" },
      { name: "Nagapattinam" },
      { name: "Namakkal" },
      { name: "Nilgiris" },
      { name: "Perambalur" },
      { name: "Pudukkottai" },
      { name: "Ramanathapuram" },
      { name: "Ranipet" },
      { name: "Salem" },
      { name: "Sivaganga" },
      { name: "Tenkasi" },
      { name: "Thanjavur" },
      { name: "Theni" },
      { name: "Thoothukudi" },
      { name: "Tiruchirappalli" },
      { name: "Tirunelveli" },
      { name: "Tirupattur" },
      { name: "Tiruppur" },
      { name: "Tiruvallur" },
      { name: "Tiruvannamalai" },
      { name: "Tiruvarur" },
      { name: "Vellore" },
      { name: "Viluppuram" },
      { name: "Virudhunagar" },
    ],
  },
  {
    name: "Telangana",
    code: "TS",
    districts: [
      { name: "Adilabad" },
      { name: "Bhadradri Kothagudem" },
      { name: "Hyderabad" },
      { name: "Jagtial" },
      { name: "Jangaon" },
      { name: "Jayashankar" },
      { name: "Jogulamba" },
      { name: "Kamareddy" },
      { name: "Karimnagar" },
      { name: "Khammam" },
      { name: "Komaram Bheem" },
      { name: "Mahabubabad" },
      { name: "Mahbubnagar" },
      { name: "Mancherial" },
      { name: "Medak" },
      { name: "Medchal" },
      { name: "Mulugu" },
      { name: "Nagarkurnool" },
      { name: "Nalgonda" },
      { name: "Narayanpet" },
      { name: "Nirmal" },
      { name: "Nizamabad" },
      { name: "Peddapalli" },
      { name: "Rajanna Sircilla" },
      { name: "Rangareddy" },
      { name: "Sangareddy" },
      { name: "Siddipet" },
      { name: "Suryapet" },
      { name: "Vikarabad" },
      { name: "Wanaparthy" },
      { name: "Warangal Rural" },
      { name: "Warangal Urban" },
      { name: "Yadadri Bhuvanagiri" },
    ],
  },
  {
    name: "Tripura",
    code: "TR",
    districts: [
      { name: "Dhalai" },
      { name: "Gomati" },
      { name: "Khowai" },
      { name: "North Tripura" },
      { name: "Sepahijala" },
      { name: "South Tripura" },
      { name: "Unakoti" },
      { name: "West Tripura" },
    ],
  },
  {
    name: "Uttar Pradesh",
    code: "UP",
    districts: [
      { name: "Agra" },
      { name: "Aligarh" },
      { name: "Ambedkar Nagar" },
      { name: "Amethi" },
      { name: "Amroha" },
      { name: "Auraiya" },
      { name: "Ayodhya" },
      { name: "Azamgarh" },
      { name: "Baghpat" },
      { name: "Bahraich" },
      { name: "Ballia" },
      { name: "Balrampur" },
      { name: "Banda" },
      { name: "Barabanki" },
      { name: "Bareilly" },
      { name: "Basti" },
      { name: "Bhadohi" },
      { name: "Bijnor" },
      { name: "Budaun" },
      { name: "Bulandshahr" },
      { name: "Chandauli" },
      { name: "Chitrakoot" },
      { name: "Deoria" },
      { name: "Etah" },
      { name: "Etawah" },
      { name: "Farrukhabad" },
      { name: "Fatehpur" },
      { name: "Firozabad" },
      { name: "Gautam Buddha Nagar" },
      { name: "Ghaziabad" },
      { name: "Ghazipur" },
      { name: "Gonda" },
      { name: "Gorakhpur" },
      { name: "Hamirpur" },
      { name: "Hapur" },
      { name: "Hardoi" },
      { name: "Hathras" },
      { name: "Jalaun" },
      { name: "Jaunpur" },
      { name: "Jhansi" },
      { name: "Kannauj" },
      { name: "Kanpur Dehat" },
      { name: "Kanpur Nagar" },
      { name: "Kasganj" },
      { name: "Kaushambi" },
      { name: "Kheri" },
      { name: "Kushinagar" },
      { name: "Lalitpur" },
      { name: "Lucknow" },
      { name: "Maharajganj" },
      { name: "Mahoba" },
      { name: "Mainpuri" },
      { name: "Mathura" },
      { name: "Mau" },
      { name: "Meerut" },
      { name: "Mirzapur" },
      { name: "Moradabad" },
      { name: "Muzaffarnagar" },
      { name: "Pilibhit" },
      { name: "Pratapgarh" },
      { name: "Prayagraj" },
      { name: "Raebareli" },
      { name: "Rampur" },
      { name: "Saharanpur" },
      { name: "Sambhal" },
      { name: "Sant Kabir Nagar" },
      { name: "Shahjahanpur" },
      { name: "Shamli" },
      { name: "Shravasti" },
      { name: "Siddharthnagar" },
      { name: "Sitapur" },
      { name: "Sonbhadra" },
      { name: "Sultanpur" },
      { name: "Unnao" },
      { name: "Varanasi" },
    ],
  },
  {
    name: "Uttarakhand",
    code: "UK",
    districts: [
      { name: "Almora" },
      { name: "Bageshwar" },
      { name: "Chamoli" },
      { name: "Champawat" },
      { name: "Dehradun" },
      { name: "Haridwar" },
      { name: "Nainital" },
      { name: "Pauri Garhwal" },
      { name: "Pithoragarh" },
      { name: "Rudraprayag" },
      { name: "Tehri Garhwal" },
      { name: "Udham Singh Nagar" },
      { name: "Uttarkashi" },
    ],
  },
  {
    name: "West Bengal",
    code: "WB",
    districts: [
      { name: "Alipurduar" },
      { name: "Bankura" },
      { name: "Birbhum" },
      { name: "Cooch Behar" },
      { name: "Dakshin Dinajpur" },
      { name: "Darjeeling" },
      { name: "Hooghly" },
      { name: "Howrah" },
      { name: "Jalpaiguri" },
      { name: "Jhargram" },
      { name: "Kalimpong" },
      { name: "Kolkata" },
      { name: "Malda" },
      { name: "Murshidabad" },
      { name: "Nadia" },
      { name: "North 24 Parganas" },
      { name: "Paschim Bardhaman" },
      { name: "Paschim Medinipur" },
      { name: "Purba Bardhaman" },
      { name: "Purba Medinipur" },
      { name: "Purulia" },
      { name: "South 24 Parganas" },
      { name: "Uttar Dinajpur" },
    ],
  },
  // Union Territories
  {
    name: "Andaman and Nicobar Islands",
    code: "AN",
    districts: [{ name: "Nicobar" }, { name: "North and Middle Andaman" }, { name: "South Andaman" }],
  },
  {
    name: "Chandigarh",
    code: "CH",
    districts: [{ name: "Chandigarh" }],
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    code: "DN",
    districts: [{ name: "Dadra and Nagar Haveli" }, { name: "Daman" }, { name: "Diu" }],
  },
  {
    name: "Delhi",
    code: "DL",
    districts: [
      { name: "Central Delhi" },
      { name: "East Delhi" },
      { name: "New Delhi" },
      { name: "North Delhi" },
      { name: "North East Delhi" },
      { name: "North West Delhi" },
      { name: "Shahdara" },
      { name: "South Delhi" },
      { name: "South East Delhi" },
      { name: "South West Delhi" },
      { name: "West Delhi" },
    ],
  },
  {
    name: "Jammu and Kashmir",
    code: "JK",
    districts: [
      { name: "Anantnag" },
      { name: "Bandipora" },
      { name: "Baramulla" },
      { name: "Budgam" },
      { name: "Doda" },
      { name: "Ganderbal" },
      { name: "Jammu" },
      { name: "Kathua" },
      { name: "Kishtwar" },
      { name: "Kulgam" },
      { name: "Kupwara" },
      { name: "Poonch" },
      { name: "Pulwama" },
      { name: "Rajouri" },
      { name: "Ramban" },
      { name: "Reasi" },
      { name: "Samba" },
      { name: "Shopian" },
      { name: "Srinagar" },
      { name: "Udhampur" },
    ],
  },
  {
    name: "Ladakh",
    code: "LA",
    districts: [{ name: "Kargil" }, { name: "Leh" }],
  },
  {
    name: "Lakshadweep",
    code: "LD",
    districts: [{ name: "Lakshadweep" }],
  },
  {
    name: "Puducherry",
    code: "PY",
    districts: [{ name: "Karaikal" }, { name: "Mahe" }, { name: "Puducherry" }, { name: "Yanam" }],
  },
];

// Helper functions
export const getStateByName = (stateName: string): State | undefined => {
  return INDIAN_STATES_WITH_DISTRICTS.find((state) => state.name === stateName);
};

export const getDistrictsByState = (stateName: string): District[] => {
  const state = getStateByName(stateName);
  return state ? state.districts : [];
};

export const getAllStates = (): string[] => {
  return INDIAN_STATES_WITH_DISTRICTS.map((state) => state.name);
};

export const getAllDistricts = (): string[] => {
  return INDIAN_STATES_WITH_DISTRICTS.flatMap((state) => state.districts.map((district) => district.name));
};

// Validation helper
export const isValidStateDistrictCombination = (stateName: string, districtName: string): boolean => {
  const districts = getDistrictsByState(stateName);
  return districts.some((district) => district.name === districtName);
};
